apiVersion: v1
kind: ReplicationController
metadata:
  name: k8stress
  namespace: k8stress
  labels:
    heritage: k8stress
spec:
  replicas: 1
  selector:
    app: k8stress
  template:
    metadata:
      labels:
        app: k8stress
    spec:
      containers:
        - name: k8stress
          image: quay.io/arschles/k8stress:devel
          imagePullPolicy: Always
          env:
            - name: "NUM_GOROUTINES"
              value: "1000"
            - name: "NAMESPACE"
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
